### ISSUE TITLE
Mounts denied in Mac

### ISSUE THREAD

**Issue by quiquisolis** [ajardin/docker-symfony#2]
Hi!, I can´t start php service, throw next error:

ERROR: for 711b4381a997_symfony_php_1  Cannot start service php: b'Mounts denied: { errno = [EACCES]; call = getattrlist; label = /private/var/root/.ssh }'

ERROR: for php  Cannot start service php: b'Mounts denied: { errno = [EACCES]; call = getattrlist; label = /private/var/root/.ssh }'
ERROR: Encountered errors while bringing up the project.

**Comment by ajardin** [comment]
Hello!

Can you describe a bit the environment where this error occurred?
And did you change anything after cloning the environment, especially in the `docker-compose.yml` file?

**Comment by aureliengiry** [comment]
I had the same issue on osx : 

```
ERROR: for symfony_php_1_8968e48431de  Cannot start service php: b'Mounts denied: \r\nThe path /Users/aureliengiry/.ssh\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for php  Cannot start service php: b'Mounts denied: \r\nThe path /Users/aureliengiry/.ssh\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
```
To solve the issue, I just add my _.ssh_ folder into docker shared folder list

Doc for osx : https://docs.docker.com/docker-for-mac/osxfs/#namespaces

**Comment by ajardin** [comment]
It's weird because according to Docker documentation:
```
By default, you can share files in /Users/, /Volumes/, /private/, and /tmp directly.
```
... 😕

**Comment by aureliengiry** [comment]
In my case, it’s because I updated default settings
