### ISSUE TITLE
PHP image build fails

### ISSUE THREAD

**Issue by vstanchev** [ajardin/docker-symfony#3]
**Describe the bug**
The PHP image fails to build with an error `configure: error: jpeglib.h not found.`

**To Reproduce**
1. Execute `make build`.

**Comment by nurusanwe** [comment]
Same issue here, if anyone knows how to solve it ? 
libjpeg-turbo-dev seems to appear in the PHP Dockerfile ... I've tried to add libjpeg-turbo8 but it didn't work neither
